NAME = depot-decentralized-pension

TEXTSRCS = depot-decentralized-pension.tex 
TEXTSRCS += _title.tex
TEXTSRCS += _abstract.tex
TEXTSRCS += _intrduction.tex
TEXTSRCS += _spec-payment.tex
TEXTSRCS += _spec-payout.tex
TEXTSRCS += _simulations.tex
TEXTSRCS += _conclusion.tex
TEXTSRCS += _futurework.tex

BIBTEXSRCS = _bibliography.bib

.include "/usr/local/share/latex-mk/latex.mk"
